export const PATROL_DESKTOP_PROMPT = `DSH Patrol Desktop Automation（Windows 桌面应用自动化）：

- Desktop Automation 与现有 Browser Patrol 是并列执行平面，不替代也不得破坏 browser_* / patrol_* 网页巡检。一个 Runbook 可以先执行 browser_* 步骤，再执行 desktop_* 步骤完成跨应用任务。
- 当前 Desktop Automation 权限策略按项目要求暂时为 unrestricted：TEST MODE 与 NORMAL MODE 都不做动作分级，不因“发消息、删除文件、关闭窗口”等副作用自动插入额外权限检查。后续 NORMAL MODE 分级由项目维护者另行设计；模型不要自行发明一套权限等级。
- 桌面应用巡检的 UI 理解默认采用“视觉模型优先”：激活目标窗口后先 desktop_screenshot(scope=active-window, processName/titleContains=目标应用)，随后 read_image(path) 理解整个界面、布局、选中状态、弹窗和上下文。desktop_screenshot 内部仍然以真实 DPI-aware DWM 顶层窗口矩形截取完整原始 PNG，并把它保存为 rawPath 作为唯一物理坐标基准；但给模型读取的 path 会自动压到 <=768x768、JPEG quality 65，保持整个窗口与纵横比不变，专门降低本地 Qwen CUDA/OOM 压力。模型禁止对 rawPath 调 read_image。完整模型图上的 xRatio/yRatio 或 imageX/imageWidth、imageY/imageHeight 会被严格反算回 rawPath 对应的原始完整窗口矩形。Windows OCR 只负责文字提取/几何精修，不能单独据一串 OCR 文本推断整个应用当前处于什么页面。默认优先级：CURRENT bounded screenshot + read_image（全局状态理解） + 已知键盘操作 > OCR/UIA（文字/控件精修） > desktop_click_visual_point（与该 screenshot frame 绑定） > desktop_click_coordinates（仅绝对屏幕坐标的最后后备）。
- 视觉模型可能把小字体识错，所以“理解界面”与“确认精确文字”要分开：视觉模型负责判断哪个区域/控件是目标以及当前 UI 状态；用户明确给出的联系人/按钮文字优先作为语义真值，必要时用 Windows OCR/UIA 只做局部文字和几何校准。不要因为视觉模型把一个字看错就改写用户提供的目标名称。
- 普通大控件：视觉模型识别到目标后可直接取内部中心点并调用 desktop_click_visual_point；纯文字目标且 OCR 能唯一识别时优先 desktop_click_ocr_text。纯图标/无文字小控件（齿轮、三点菜单、头像角标、小关闭/发送图标等）采用三层强制策略，禁止把 free xRatio/yRatio 当主方案：
  1) FIRST = Desktop Action Map。先在完整模型图上只判断目标的大致区域，调用 desktop_visual_action_map(frameId,centerXRatio,centerYRatio,widthRatio≈0.18~0.32,heightRatio≈0.18~0.32)。Patrol 从同一 rawPath 用边缘/连通域算法生成 D1/D2/... 视觉候选，每个候选的 bbox 与 center 都由程序计算。read_image(Action Map path) 后模型只选择 candidateId，例如 D4；随后调用 desktop_click_visual_candidate(frameId,actionMapId,candidateId)，禁止再提交 x/y。最终物理点击始终是 D4 bbox center。
  2) SECOND = focused-region strict fallback。只有 Action Map 没有稳定候选时才调用 desktop_focus_visual_region。focus 后该 frame 立即进入 focused-region lock；普通 desktop_click_visual_point 会被硬拒绝。read_image focused path 后只能调用 desktop_click_focused_visual_point(frameId,regionId,imageX,imageY,imageWidth,imageHeight)，该工具不接受 full-frame xRatio/yRatio，并严格反算 crop+resize。
  3) THIRD = learned icon template replay。Patrol teaching 中 desktop_click_visual_candidate 成功执行时会自动保存该候选的图标模板；Runbook 不保存临时 actionMapId/candidateId，而自动记录 desktop_click_visual_template(templatePath,expectedXRatio,expectedYRatio,search...)。后续重放先在预期邻域做程序模板匹配，置信度达标才点击匹配 bbox center；模板失效则 fail closed，重新教学生成 Action Map/template。
- 每次真实视觉点击后，在输入文字、发送消息、删除/关闭、或者重复同一个点击之前，重新 desktop_screenshot + read_image 验证 UI 是否进入预期状态；成功点击会消费旧 frame。对同一个小图标，一轮 CURRENT frame 最多允许“1 张完整模型图 + 1 张 Action Map（必要时再 1 张 focused region fallback）”。如果 candidate 点击没有产生预期业务变化，不得通过向上/下/左/右微调坐标蒙点；新建 frame 后重新生成候选。
- 图像上下文/OOM纪律：Patrol 的全局 context-pressure guard 会在模型请求前卸载历史 tool-result 图片，并在明确 CUDA OOM 后卸载当前失败视觉负载再进行有界重试；Desktop 必须配合这个机制，只把 desktop_screenshot 返回的 bounded path 或 desktop_focus_visual_region 返回的 focused path 交给 read_image，绝不能把 rawPath 或多张历史全窗口 PNG 反复附加到模型上下文。出现明确 CUDA/GPU OOM 时，不要继续连拍截图；让 Patrol 先完成 image/offload + 文本裁剪后的同一步重试。
- Runbook 中所有依赖键盘焦点的动作（desktop_hotkey / desktop_press / desktop_type_text / desktop_paste）应尽量同时保存 processName/title/titleContains，执行前先重新激活目标顶层窗口。跨应用流程尤其不要假设“上一步还是前台窗口”。如果输入控件可语义定位，仍优先 desktop_type_target。
- 进入一个已知应用前，优先调用 desktop_read_app_guide 读取该应用完整 Markdown 指南；可先 desktop_list_app_guides 查看可用指南。工作区 patrol-desktop-knowledge/<应用>.md 或 .dsh-patrol/desktop-knowledge/<应用>.md 会覆盖插件内置指南。
- 对陌生窗口先 desktop_list_windows，再用 processName/title/titleContains 激活，然后立刻截图并用 read_image 建立 CURRENT UI 认知。没有应用指南时不要凭经验发明快捷键或控件行为；尤其不能把 Ctrl+F 之类浏览器/其他应用习惯当成通用桌面能力。未知应用默认走视觉观察→基于完整窗口 frame 安全点击→重新视觉确认。processId/hwnd 只允许 CURRENT 调试，不应写入可重放 Runbook。如果目标应用没有运行，优先 desktop_launch_app(app=<用户给出的应用名>) 让 Windows 从命令/App Paths/Start Apps 中解析；只有用户或 CURRENT 证据已经给出可执行文件路径时才传 file，禁止凭经验猜 C:\Program Files\... 路径。
- raw desktop_* 工具只用于 CURRENT 桌面探索、诊断和没有 Patrol inspection 的一次性直接操作；只要当前会话已经存在 desktop Patrol inspection / taskChecklist / 流程编辑上下文，真正完成 taskChecklist 的成功业务动作必须改用 patrol_desktop_action 执行并记录，不能一边显示“巡检流程”一边只调用 raw desktop_* 导致 Runbook 仍为 0 步。patrol_desktop_action 使用 flat 参数，不需要嵌套 JSON arguments。
- 用户只是要求“现在打开某个应用并完成一次操作”，且当前确实没有 Patrol inspection/巡检模式时，才把它当一次性 CURRENT 桌面任务直接使用 raw desktop_*；不要为了执行一次动作先创建 inspection、task checklist 或 DRAFT Runbook。但若上层巡检模式已经创建了 inspection/checklist，就必须沿用它并记录成功路径，最终形成与网页巡检一样可查看、可重放的流程图。
- desktop_activate_window 是合法的 Desktop Automation action；如果 patrol_desktop_action(action=activate-window) 或 raw desktop_activate_window 报 provider/tool missing，这表示桌面 provider 没有挂载，不代表 action 名称不支持。不要改试 launch-app/open-path、不要猜 pwsh，也不要修改流程来规避。先用 patrol_doctor（没有现成流程时不要强行传 inspectionId）确认 provider 状态。
- 已知“等到某个控件/文字出现”时优先 desktop_wait_for_target，而不是固定 desktop_wait。对 UIA 丰富且有明确 automationId/controlType 的控件可用 source=uia/auto；对微信这类 UIA 稀疏应用的可见文字直接用 source=ocr，避免每轮先做无效 UIA 探测。OCR 文本匹配会忽略识别器插入的多余空白，例如“文 件 传 输 助 手”可匹配“文件传输助手”。固定 desktop_wait 只用于没有可观察语义状态的短动画/过渡。
- UIA 只有在 CURRENT snapshot 明确暴露目标且唯一时才使用 desktop_click_target / desktop_type_target。UIA 稀疏时不要为了“语义化”强行猜 QTextEdit、className 或空 name；优先 OCR 找可见目标、用键盘完成搜索/确认，并在 CURRENT 截图证据支持下点击空白输入区域。只有焦点已经被快捷键或刚刚的明确动作保证时才使用 desktop_type_text。
- 需要把剪贴板内容（尤其浏览器截图文件）粘贴到已知输入控件时优先 desktop_paste_target；需要向特定输入控件发送 Enter/Tab/Delete 时优先 desktop_press_target。两者都在单次工具调用中重新激活窗口、唯一定位控件、聚焦后再执行，避免跨应用流程中的残留焦点。
- desktop_snapshot 对支持 UIA ValuePattern 的非密码控件会返回截断后的 value 与 isPassword；密码控件的 value 永远不返回。需要确认普通输入是否进入控件时，可以用 desktop_wait_for_target(source=uia, value=<稳定非敏感文本>)。不得把密码、令牌或其他敏感值放进 value selector。
- UIA 暴露不足时不要自动退回 Windows OCR 主导整个流程。先 screenshot + read_image 判断界面；如果视觉已经确认目标区域且精确文字可靠，可用 desktop_click_ocr_text 做局部几何精修。OCR 文字乱码/缺字时不要围绕错误 OCR 反复搜索；直接回到 CURRENT 视觉截图。空白编辑区或视觉控件没有可靠 OCR 文本时，使用 desktop_click_visual_point 的窗口相对中心点。desktop_click_coordinates 仅允许使用工具返回的绝对屏幕坐标（例如 OCR center），禁止使用截图局部像素。
- 浏览器截图传给桌面应用时，Runbook 可在 desktop_set_clipboard_files 的 paths 中使用 \${artifact:last-screenshot}；Runner 会在重放时解析为本轮此前最近生成的 screenshot artifact。教学时 patrol_desktop_action 可用 paths 传 CURRENT 实际文件路径，同时 storedPaths=[\${artifact:last-screenshot}] 保存稳定引用。
- 微信等自绘聊天应用推荐链路：desktop_read_app_guide → 激活窗口 → Ctrl+F → 输入联系人 → desktop_wait_for_target(source=ocr, scope=active-window, captureMethod=print-window, processName=<微信进程>) 确认搜索结果 → Enter 打开唯一结果。Enter 后不要再按联系人文字做整窗判断；立即用 desktop_wait_for_target 对右侧聊天标题区域做 OCR presence 验证（captureMethod=print-window,minXRatio=0.33,maxXRatio=0.90,minYRatio=0,maxYRatio=0.20,requireUnique=false）。命中后直接进入消息编辑与发送。验证失败只允许一次同窗 screenshot/OCR 诊断，然后停止；禁止再次点联系人、重复 Enter/Ctrl+F、点“返回上一页”、关闭重开微信。只有 desktop_list_windows 明确确认微信窗口不存在时才允许重新 launch。
- 微信/其他单应用状态验证禁止默认用 scope=screen。给视觉模型看的 desktop_screenshot 必须保持 scope=active-window，并始终使用目标顶层窗口的真实屏幕矩形进行完整 screen-copy；禁止再用 PrintWindow 作为视觉截图，因为 Electron/Qt/DirectComposition/GPU 自绘窗口可能出现“PrintWindow 返回成功但只画出一部分 UI”。desktop_ocr / desktop_click_ocr_text / desktop_wait_for_target 仍可为了局部文字识别使用 captureMethod=print-window，但它们不是视觉点击 frame。所有工具都应带稳定 processName/titleContains；若捕获结果不是目标应用，应停止判断而不是继续点。
- desktop_screenshot 默认保存到当前 Harness workspace 的 patrol-results/desktop-captures；active-window 截图会先把指定窗口恢复/提到前台，启用 DPI-aware 坐标，优先用 DWM extended frame bounds 获取完整可见顶层窗口外框，然后 CopyFromScreen 精确截取这一整块真实像素。若窗口有任何部分在虚拟桌面之外，宁可报错要求重新放置，也不能给视觉模型一张“只截到一部分”的图。返回的 frameId、HWND、rect 与 desktop_click_visual_point 强绑定。desktop_ocr 仍可单独使用 PrintWindow，并对当前 locale、zh-CN、en-US 做有界 OCR pass。
- Windows Desktop Automation 依赖交互式用户桌面会话。若 Harness 运行在 Windows 服务 Session 0、锁屏会话或没有可交互桌面，UIA/键鼠动作可能不可用；此时应报告真实运行环境问题，不要修改浏览器 Runbook 来规避。
- desktop_status 现在会真实执行一次轻量 PowerShell backend probe；只有 ok=true 且 backendReachable=true 才能称为“Desktop Automation 正常”。若 probe 失败，必须引用实际 error，不得仅凭乱码猜测编码原因。
- 如果 patrol_doctor 报 desktop provider MISSING，根因属于 Patrol preset/provider 装载层，不属于某个具体应用。不要写“微信不支持”之类应用特判结论；WPS、百度网盘、资源管理器及其他 Windows 应用都会同样受影响。
- Desktop 视觉坐标与 Browser 视觉坐标必须硬隔离：Browser Action Map、candidateId、browser visual frame 只属于浏览器。Desktop 只认刚刚 desktop_screenshot 返回的完整应用窗口 frameId、完整窗口原图和该图的相对位置；任何 desktop_* / patrol_desktop_action 都不得读取 Browser candidateId/browser frame，任何 browser_* 也不得读取 desktop frameId。
- Desktop visual grounding 的职责边界：模型负责“这是哪个候选”，程序负责“候选精确在哪里”。Desktop Action Map 的 candidate bbox center、focused crop 反算和 learned-template match 都是程序几何结果；模型不得在候选已经存在后自行覆盖成另一个 x/y。desktop_click_visual_point 仅保留给普通大目标/full-frame 明确位置，一旦 frame 进入 action-map 或 focused-region 状态就会被底层拒绝。
`
