export const PATROL_SESSION_PROMPT = `Patrol authenticated-session and retry discipline:
- The managed Patrol Chromium profile is persistent (userDataDir under DSH_HOME/patrol/browser-profile). Site cookies, local storage, and normal browser session state persist there automatically across Patrol runs and browser restarts. Reuse that profile; never export raw cookie values into reports, Runbooks, workspace files, or model-visible text.
- After navigating to the requested target URL, prefer the existing authenticated session. For new or re-taught login flows, record patrol_login_state immediately after navigation. Condition username, credential, login-click, and login-only verification steps on that detector containing login-state=login-required. If it reports authenticated, skip the complete login branch and continue with application checks.
- Do not call browser_login_state directly from the model; browser_* calls remain nested-provider-only. patrol_login_state is the flat model-facing Patrol action.
- A successful login is sticky for the remainder of the teaching/validation/run unless the page visibly returns to a login form or the recorded login-state check reports login-required. Once application data is visible, treat login as successful and continue from that authenticated page.
- Do not repeatedly begin_edit, delete/recreate login steps, or replay login manually after a normal tool failure. Repair the actual failing step. Validation and normal replay already execute the Runbook end-to-end. Never respond to an unrelated read/count/Excel failure by starting the login sequence again.
- Existing older Runbooks may contain unconditional username/password/login-click steps. The Patrol runner defensively checks browser_login_state internally before login-looking type/click steps and treats them as passed without executing them when the persistent browser profile is already authenticated.
- If the session really expired and the login-state detector reports login-required, execute the stored login branch once. If a human verification challenge appears, use the existing verification handoff; otherwise continue. Do not loop login attempts.
- The complete reusable Runbook is not the collection of page-text/screenshots. Patrol mirrors the authoritative inspection definition to patrol-results/<inspection>/runbook/inspection.json and runbook.md, and snapshots the exact Runbook used by each run under <run>/runbook/. Future replays execute that stored step list in order.`
